import { Content } from '@/components/Content';
import {
  Avatar,
  Container,
  Dropdown,
  Link,
  Navbar,
  Text,
} from '@nextui-org/react';
import type { NextPage } from 'next';
import Head from 'next/head';

import logo from '@/app/assets/images/logo.png';
import Banner from '@/components/banner/banner';
import Features from '@/components/features/features';

const Home: NextPage = () => {
  const collapseItems = [
    'Profile',
    'Dashboard',
    'Activity',
    'Analytics',
    'System',
    'Deployments',
    'My Settings',
    'Team Settings',
    'Help & Feedback',
    'Log Out',
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar shouldHideOnScroll variant="sticky">
        <Navbar.Toggle showIn="xs" />
        <Navbar.Brand
          css={{
            '@xs': {
              w: '12%',
            },
          }}
        >
          <img src="/images/logo.png" alt="" />
        </Navbar.Brand>
        <Navbar.Content enableCursorHighlight hideIn="xs" variant="underline">
          <Navbar.Link href="#">Features</Navbar.Link>
          <Navbar.Link isActive href="#">
            Customers
          </Navbar.Link>
          <Navbar.Link href="#">Pricing</Navbar.Link>
          <Navbar.Link href="#">Company</Navbar.Link>
        </Navbar.Content>
        <Navbar.Content
          css={{
            '@xs': {
              w: '12%',
              jc: 'flex-end',
            },
          }}
        >
          <Dropdown placement="bottom-right">
            <Navbar.Item>
              <Dropdown.Trigger>
                <Avatar
                  bordered
                  as="button"
                  color="primary"
                  size="md"
                  src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
                />
              </Dropdown.Trigger>
            </Navbar.Item>
            <Dropdown.Menu
              aria-label="User menu actions"
              color="primary"
              onAction={(actionKey) => console.log({ actionKey })}
            >
              <Dropdown.Item
                key="profile"
                textValue="profile"
                css={{ height: '$18' }}
              >
                <Text b color="inherit" css={{ d: 'flex' }}>
                  Signed in as
                </Text>
                <Text b color="inherit" css={{ d: 'flex' }}>
                  zoey@example.com
                </Text>
              </Dropdown.Item>
              <Dropdown.Item key="settings" textValue="settings" withDivider>
                My Settings
              </Dropdown.Item>
              <Dropdown.Item key="team_settings" textValue="team_settings">
                Team Settings
              </Dropdown.Item>
              <Dropdown.Item key="analytics" textValue="analytics" withDivider>
                Analytics
              </Dropdown.Item>
              <Dropdown.Item key="system" textValue="system">
                System
              </Dropdown.Item>
              <Dropdown.Item key="configurations" textValue="configurations">
                Configurations
              </Dropdown.Item>
              <Dropdown.Item
                key="help_and_feedback"
                textValue="help_and_feedback"
                withDivider
              >
                Help & Feedback
              </Dropdown.Item>
              <Dropdown.Item
                key="logout"
                textValue="logout"
                withDivider
                color="error"
              >
                Log Out
              </Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
        </Navbar.Content>
        <Navbar.Collapse disableAnimation>
          {collapseItems.map((item, index) => (
            <Navbar.CollapseItem
              key={item}
              activeColor="warning"
              css={{
                color: index === collapseItems.length - 1 ? '$error' : '',
              }}
              isActive={index === 2}
            >
              <Link
                color="inherit"
                css={{
                  minWidth: '100%',
                }}
                href="#"
              >
                {item}
              </Link>
            </Navbar.CollapseItem>
          ))}
        </Navbar.Collapse>
      </Navbar>

      <Banner />

      <Container lg>
        <Features />
        <Content />
      </Container>
    </>
  );
};

export default Home;
